config/routes.rb
Rails.application.routes.draw do
  resources :todos, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'samples', to: 'application#samples'

  root to: 'application#todos'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true, uniqueness: true

  scope :complete, -> { where.not(completed_at: nil) }
  scope :incomplete, -> { where(completed_at: nil) }

  def is_completed?
    completed_at.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def todos; end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/application/samples.html.erb
<h1 class="mdc-typography--headline1">Vanilla Material Design</h1>
<p>
  This vanilla Material Design html tag examples.
</p>

<div class="mdc-layout-grid">
  <div class="mdc-layout-grid__inner">
    <div class="mdc-layout-grid__cell--span-12" style="text-align: center;">
      <button class="mdc-button mdc-button--raised"
              data-mdc-auto-init="MDCRipple">
        <div class="mdc-button__ripple"></div>
        <span class="mdc-button__label">Hello</span>
      </button>
    </div>

    <div class="mdc-layout-grid__cell--span-4">
      <label class="mdc-text-field mdc-text-field--filled" style="width: 100%"
             data-mdc-auto-init="MDCTextField">
        <span class="mdc-text-field__ripple"></span>
        <input type="text"
               class="mdc-text-field__input"
               aria-labelledby="username-label"
               name="username"
               required>
        <span class="mdc-floating-label"
              id="username-label">Username</span>
        <span class="mdc-line-ripple"></span>
      </label>
    </div>

    <div class="mdc-layout-grid__cell--span-4 mdc-layout-grid__cell--align-middle" style="text-align: center;">
      <div class="mdc-form-field">
        <div class="mdc-checkbox"
             data-mdc-auto-init="MDCCheckbox">
          <input type="checkbox"
                 class="mdc-checkbox__native-control"
                 id="checkbox-1"/>
          <div class="mdc-checkbox__background">
            <svg class="mdc-checkbox__checkmark"
                 viewBox="0 0 24 24">
              <path class="mdc-checkbox__checkmark-path"
                    fill="none"
                    d="M1.73,12.91 8.1,19.28 22.79,4.59"/>
            </svg>
            <div class="mdc-checkbox__mixedmark"></div>
          </div>
          <div class="mdc-checkbox__ripple"></div>
        </div>
        <label for="checkbox-1">Checkbox 1</label>
      </div>
    </div>

    <div class="mdc-layout-grid__cell--span-4">
      <div class="mdc-select mdc-select--filled demo-width-class" data-mdc-auto-init="MDCSelect" style="width: 100%">
        <div class="mdc-select__anchor"
             role="button"
             aria-haspopup="listbox"
             aria-expanded="false"
             aria-labelledby="demo-label demo-selected-text">
          <span class="mdc-select__ripple"></span>
          <span id="demo-label" class="mdc-floating-label">Pick a Food Group</span>
          <span class="mdc-select__selected-text-container">
      <span id="demo-selected-text" class="mdc-select__selected-text"></span>
    </span>
          <span class="mdc-select__dropdown-icon">
      <svg
        class="mdc-select__dropdown-icon-graphic"
        viewBox="7 10 10 5" focusable="false">
        <polygon
          class="mdc-select__dropdown-icon-inactive"
          stroke="none"
          fill-rule="evenodd"
          points="7 10 12 15 17 10">
        </polygon>
        <polygon
          class="mdc-select__dropdown-icon-active"
          stroke="none"
          fill-rule="evenodd"
          points="7 15 12 10 17 15">
        </polygon>
      </svg>
    </span>
          <span class="mdc-line-ripple"></span>
        </div>

        <div class="mdc-select__menu mdc-menu mdc-menu-surface mdc-menu-surface--fullwidth">
          <ul class="mdc-list" role="listbox" aria-label="Food picker listbox">
            <li class="mdc-list-item mdc-list-item--selected" aria-selected="true" data-value="" role="option">
              <span class="mdc-list-item__ripple"></span>
            </li>
            <li class="mdc-list-item" aria-selected="false" data-value="grains" role="option">
              <span class="mdc-list-item__ripple"></span>
              <span class="mdc-list-item__text">
          Bread, Cereal, Rice, and Pasta
        </span>
            </li>
            <li class="mdc-list-item mdc-list-item--disabled" aria-selected="false" data-value="vegetables" aria-disabled="true" role="option">
              <span class="mdc-list-item__ripple"></span>
              <span class="mdc-list-item__text">
          Vegetables
        </span>
            </li>
            <li class="mdc-list-item" aria-selected="false" data-value="fruit" role="option">
              <span class="mdc-list-item__ripple"></span>
              <span class="mdc-list-item__text">
          Fruit
        </span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/todos.html.erb
<h1>TODOS</h1>
<p>
  Sample application utilizing Stimulus JS, Action Cable Reflexes, Rails View Component. All in Material Design from Materialize framework.
</p>
<h3>Features</h3>
<ul>
  <li><i class="tiny material-icons left">done</i>adding new todo item</li>
  <li><i class="tiny material-icons left">done</i>todo item validation: title presence and uniqueness</li>
  <li><i class="tiny material-icons left">done</i>title edition of incomplete todo item</li>
  <li><i class="tiny material-icons left">done</i>todo item list filtering: all, complete, incomplete</li>
  <li><i class="tiny material-icons left">done</i>marking todo item as complete/incomplete</li>
  <li><i class="tiny material-icons left">done</i>removing of all complete todo items</li>
  <li><i class="tiny material-icons left">done</i>information about how many incomplete todo items left</li>
</ul>
<hr />
<%= link_to '<i class="material-icons left">format_list_bulleted</i>&nbsp;open Todos'.html_safe, todos_path, class: 'waves-effect waves-light btn' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todos :: ComponentView + Stimulus + Reflexes</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav>
  <div class="nav-wrapper">
    <%= link_to 'Home', root_url, class: 'brand-logo' %>
    <a href="#" data-target="mobile-nav" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul id="nav-mobile" class="right hide-on-small-only">
      <li><%= link_to 'Todos', todos_path %></li>
    </ul>
  </div>
</nav>

<ul class="sidenav" id="mobile-nav" data-turbolinks-permanent>
  <li><%= link_to 'Todos', todos_path %></li>
</ul>

<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/todos/index.html.erb
<h1>Todos component example</h1>
<%= render TodosComponent.new %>